/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.audio;

import javax.sound.sampled.*;
import java.util.Arrays;
import java.util.Locale;

public class App {

    public static void main(String[] args) {
        Mixer.Info[] mixerInfo = AudioSystem.getMixerInfo();    //get available mixers
        System.out.println("Available mixers:");
        for (int i = 0; i < mixerInfo.length; ++i) {
            Mixer.Info info = mixerInfo[i];
            System.out.println();
            System.out.println(String.format(Locale.US,
                    "mixerInfo num: %02d \ndescr: <%s> \nname: <%s> \nvend: <%s> \nver: <%s>",
                    i,
                    info.getDescription(),
                    info.getName(),
                    info.getVendor(),
                    info.getVersion()
            ));
            Mixer mixer = AudioSystem.getMixer(info);
            Line.Info[] srcLinesInfo = mixer.getSourceLineInfo();
            System.out.println("srcLinesInfo cnt: " + srcLinesInfo.length);
            for (int i1 = 0; i1 < srcLinesInfo.length; i1++) {
                System.out.println(String.format(Locale.US,
                        "srcLineInfo num: %02d srcLineInfo: <%s>",
                        i1, srcLinesInfo[i1].toString()
                ));
            }
            Line.Info[] dstLinesInfo = mixer.getTargetLineInfo();
            System.out.println("dstLinesInfo cnt: " + dstLinesInfo.length);
            for (int i1 = 0; i1 < dstLinesInfo.length; i1++) {
                System.out.println(String.format(Locale.US,
                        "dstLineInfo num: %02d dstLineInfo: <%s>",
                        i1, dstLinesInfo[i1].toString()
                ));
            }
            TargetDataLine dst = null;
            SourceDataLine src = null;
            AudioFormat format = audioFormat();
            try {
                dst = AudioSystem.getTargetDataLine(format, info);
                System.out.println("dstDataLine OK " + dst.getLineInfo());
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                src = AudioSystem.getSourceDataLine(format, info);
                System.out.println("srcDataLine OK " + src.getLineInfo());
            } catch (Exception e) {
                e.printStackTrace();
            }
            loopBack(dst, src, format.getFrameSize());
        }
        System.out.println();
    }

    static private final long CHECK_PERIOD = 2000;

    private static void loopBack(TargetDataLine dst, SourceDataLine src, int frameSize) {
        if (dst == null || src == null)
            return;
        try {
            dst.start();
            src.start();
            long startTs = System.currentTimeMillis();
            while (System.currentTimeMillis() - startTs < CHECK_PERIOD) {
                byte[] data = new byte[frameSize];
                boolean isEmpty = true;
                int read = dst.read(data, 0, frameSize);
                if (read == 0)
                    continue;
                for (byte datum : data) {
                    if (datum != 0) {
                        isEmpty = false;
                        break;
                    }
                }
                if (isEmpty)
                    continue;
                System.out.println("read: " + Arrays.toString(data));
                src.write(data, 0, frameSize);
                System.out.println("written");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            dst.close();
            src.close();
        }
    }

    private static AudioFormat audioFormat() {
        float sampleRate = 32000.0F;
        int sampleSizeInBits = 16;
        int channels = 2;
        boolean signed = true;
        boolean bigEndian = false;
        return new AudioFormat(sampleRate, sampleSizeInBits, channels, signed, bigEndian);
    }

}
